from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest
import os

"""
This pytest test was automatically generated by TestProject
    Project: siq
    Package: TestProject.Generated.Tests.Siq
    Test: siq-tests
    Generated by: Rahul Kumar (rahulknit1994@gmail.com)
    Generated on 10/28/2021, 11:38:34
"""

api_token = os.getenv("API_TOKEN")

@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token=api_token,
                              project_name="siq",
                              job_name="siq-tests")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://siq04-lb-vip.cloud.in.guavus.com/siq/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Keycloak' present?
    keycloak = driver.find_element(By.XPATH,
                                   "//div[. = 'Keycloak']")

    # 3. Is 'Username1' present?
    username1 = driver.find_element(By.XPATH,
                                    "//label[. = 'Username']")

    # 4. Is 'Password1' present?
    password1 = driver.find_element(By.XPATH,
                                    "//label[. = 'Password']")

    # 5. Click 'username'
    username = driver.find_element(By.CSS_SELECTOR,
                                   "#username")
    username.click()

    # 6. Type 'cisco-admin' in 'username'
    username = driver.find_element(By.CSS_SELECTOR,
                                   "#username")
    username.send_keys("cisco-admin")

    # 7. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 8. Type 'cisco-admin' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("cisco-admin")

    # 9. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 10. Is 'login' is clickable?
    login = driver.find_element(By.CSS_SELECTOR,
                                "#kc-login")
    assert login.is_enabled()

    # 11. Click 'login'
    login = driver.find_element(By.CSS_SELECTOR,
                                "#kc-login")
    login.click()

    # 12. Is 'Fill-6' is clickable?
    fill_6 = driver.find_element(By.CSS_SELECTOR,
                                 "#Fill-6")
    assert fill_6.is_enabled()

    # 13. Click 'Fill-6'
    fill_6 = driver.find_element(By.CSS_SELECTOR,
                                 "#Fill-6")
    fill_6.click()

    # 14. Is 'Logout1' is clickable?
    logout1 = driver.find_element(By.XPATH,
                                  "//button[. = ' Logout ']")
    assert logout1.is_enabled()

    # 15. Click 'Logout1'
    logout1 = driver.find_element(By.XPATH,
                                  "//button[. = ' Logout ']")
    logout1.click()

    # 16. Close window with index '[NONE]'
    driver.close()
